language: cpp
dist: bionic

compiler:
  - clang
  - gcc

install:
  - sudo apt update
  - sudo apt install -y libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libphysfs-dev

script:
  - mkdir -p build && cd build
  - cmake ..
  - make
